#CI项目
name: QCA-6.18-Docker

#CI计划
on:
  #自动编译：当Auto-Clean运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  #手动编译
  workflow_dispatch:

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.CONFIG}}
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-WIFI]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      #编译配置
      WRT_CONFIG: ${{matrix.CONFIG}}
      #默认主题
      WRT_THEME: argon
      #默认主机名
      WRT_NAME: Vipkj-WRT
      #默认WIFI名称
      WRT_SSID: Vipkj-WRT
      #默认WIFI密码
      WRT_WORD: 12345678
      #默认地址
      WRT_IP: 192.168.1.2
      #默认密码
      WRT_PW: password
      #源码链接
      WRT_REPO: https://github.com/${{matrix.SOURCE}}.git
      #源码分支
      WRT_BRANCH: ${{matrix.BRANCH}}
      #源码名称
      WRT_SOURCE: ${{matrix.SOURCE}}
      #禁用插件
      WRT_DISABLE: luci-app-daed luci-app-dae daed dae
      #仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}

      CI_NAME: ${{github.workflow}}
